### ISSUE TITLE
Using HtmlTags?

### ISSUE THREAD

**Issue by KevinBurton** [amoerie/HtmlBuilders#5]
I installed the NuGet Package but the line 'HtmlTags.Div.Class("autofillContainer")' will not compile and the Div identifier is red as undefined in VS.

            var container = HtmlTags.Div.Class("autofillContainer");

**Comment by amoerie** [comment]
Which version of .NET are you using? Which Visual Studio version are you using?
I just made a small test project in Visual Studio 2013 using .NET 4.5.2 and it works fine.

My packages.config:

    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="HtmlAgilityPack" version="1.4.6" targetFramework="net45" />
      <package id="HtmlBuilders" version="2.0.5" targetFramework="net45" />
      <package id="Microsoft.AspNet.Mvc" version="4.0.20505.0" targetFramework="net45" />
      <package id="Microsoft.AspNet.Razor" version="2.0.20505.0" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebPages" version="2.0.20505.0" targetFramework="net45" />
      <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
      <package id="NUnit" version="2.6.4" targetFramework="net45" />
    </packages>

Note that the versions are the minimum required versions, not the most up to date ones. 
If you are completely up to date, it would look something like this:

    <?xml version="1.0" encoding="utf-8"?>
    <packages>
      <package id="HtmlAgilityPack" version="1.4.9" targetFramework="net45" />
      <package id="HtmlBuilders" version="2.0.5" targetFramework="net45" />
      <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net45" />
      <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net45" />
      <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net45" />
      <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net45" />
      <package id="NUnit" version="2.6.4" targetFramework="net45" />
    </packages>

My test class:

    using HtmlBuilders;
    using NUnit.Framework;

    namespace HtmlBuildersTest {
      [TestFixture]
      public class TestsForHtmlBuilders {
        [Test]
        public void SimpleToStringTest() {
          var div = HtmlTags.Div.Class("alrightie");
          Assert.That(div.ToString(), Is.EqualTo("<div class=\"alrightie\"></div>"));
        }
      }
    }

All is green.

It's probably an issue with your solution or setup, although I'm not excluding the possibility that HtmlBuilders is somehow not compatible with your environment. 

Please provide more details if you want me to look at this in detail.

**Comment by KevinBurton** [comment]
The target framework is 4.0. I am running VS 2013. I installed the package HtmlTags with NuGet. I was unable to find HtmlBuilders?

Kevin

**Comment by amoerie** [comment]
Ah I see what is going on. Currently, HtmlBuilders does not support .NET 4.0, only 4.5 and up. You installed something else.

This is my package: https://www.nuget.org/packages/HtmlBuilders/
This is what you tried to install: https://www.nuget.org/packages/HtmlTags/

I might have a look if HtmlBuilders would work on .NET 4.0 but I'm not making any promises. I'll have a look sometime this week when I find the time!
