### ISSUE TITLE
Append html text "as-is" without encoding

### ISSUE THREAD

**Issue by AceTheWiz** [amoerie/HtmlBuilders#58]
Hi, thanks for the library.

Is there a way to append html text to a tag without it being encoded.
## Scenario 1

```C#
.Append(HtmlTags.Script.Append(new HtmlString("var pathToToc = \"/toc-placeholder.json\";")))
```
Actual html
```html
<script>var pathToToc = &#x27;/toc-placeholder.json&#x27;;</script>
```
Expected html
```html
<script>var pathToToc = "/toc-placeholder.json";</script>
```
## Scenario 2
I have a function which returns a table of contents already in html. (i.e a nested unordered list) 
```C#
.Append(HtmlTags.Div.Class("table-of-contents").Append(GetTableOfContents())))
```
This produces encoded html.

How do I prevent the Append function from encoding.

Is there an ```AppendAsHtml()``` perhaps ?

**Comment by amoerie** [comment]
On mobile right now, but you should be able to append IHtmlContent. One of
the implementation of IHtmlContent is HtmlString, which is already encoded.

Op wo 3 feb. 2021 20:42 schreef AceTheWiz <notifications@github.com>:

**Comment by AceTheWiz** [comment]
Thanks for the quick reply.
If you look at **Scenario 1**, I did try use ```HtmlString``` but the result is the same ? Am I doing it wrong ?

**Comment by amoerie** [comment]
Here is a unit test that verifies what you want should work:

```csharp
      [Fact]
      public void AppendingHtmlContent_ShouldAppendCorrectly() {
        IHtmlContent hiDoctorNick = new HtmlString("<div>Hi doctor Nick!</div>");
        HtmlTag hiEverybody = HtmlTag.Parse("<div>Hi everybody!</div>");

        var result = hiEverybody.Append(hiDoctorNick);

        result.ToHtmlString().Should().Be("<div>Hi everybody!<div>Hi doctor Nick!</div></div>");
      }
```

**Comment by amoerie** [comment]
Looks like you found a bug! When free text is parsed using HtmlAgilityPack, it was passed as a string to HtmlText.
When HtmlText then writes to the output, it encodes the string.

Nice find! Can you please try to use HtmlBuilders 6.0.1 and see if it fixes your problem? I added some unit tests that indicate it works now.

**Comment by AceTheWiz** [comment]
Thank you very much Alexander it now works as expected. I was at the point of giving up and going back to using horrible & error prone ```WriteLine``` again. Now I am happy 😀 .
Your library is the most natural and logical implementation I have come across (I looked at many HtmlBuilders).

p.s Could you look at [Issue 57](https://github.com/amoerie/HtmlBuilders/issues/57#issue-800186500) please.

**Comment by ortrails** [comment]
When I do that for `&nbsp;` I get unicode U+00A0 no-break space character. That seems incorrect when i want the `&nbsp;`
