### ISSUE TITLE
Object to HTML Table transforms

### ISSUE THREAD

**Issue by andywilsonuk** [amoerie/HtmlBuilders#6]
Hi,

Any chance you can create an extension to convert an ```IEnumerable<T>``` into an HTML Table? Using reflection, the headers values can be determined by the property names and the data values from the property values.

What do you think?

Cheers
Andy

**Comment by amoerie** [comment]
Hey Andy,

two notes on that:

- First of all, it sure would be possible! As you say though, this would be an extension. I don't really see why anyone but me would be able to make this. 

However, I'll play nice and did a quick writeup for you! 

```csharp
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;

    namespace HtmlBuilders.ToTableExtension {
      public class Person {
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public Person(string firstName, string lastName) {
          FirstName = firstName;
          LastName = lastName;
        }
      }

      public static class App {
        public static void Main(String[] args) {
          var people = new[] {
            new Person("Jack", "Daniels"),
            new Person("Jennifer", "Lawrence"),
            new Person("Andy", "Wilson"),
          };

          var properties = GetProperties(typeof (Person)).ToList();
          var table = HtmlTags.Table
            .Append(CreateHeader(properties))
            .Append(CreateBody(properties, people));
          var html = table.ToHtml();
        }

        private static IEnumerable<PropertyInfo> GetProperties(Type type) {
          return type.GetProperties(BindingFlags.Instance | BindingFlags.Public);
        } 

        private static HtmlTag CreateHeader(IEnumerable<PropertyInfo> properties) {
          return HtmlTags.Thead.Append(properties.Aggregate(HtmlTags.Tr, (tr, property) => tr.Append(HtmlTags.Td.Append(property.Name))));
        }

        private static HtmlTag CreateBody<T>(IEnumerable<PropertyInfo> properties, IEnumerable<T> records) {
          return records.Aggregate(HtmlTags.Tbody, (body, record) => body.Append(
            properties.Aggregate(HtmlTags.Tr,
              (tr, property) => tr.Append(HtmlTags.Td.Append(Convert.ToString(property.GetValue(record)))))));
        }

      }
    }

```

Note 2: If you want more advanced scenarios, I suggest you take a look at my other (unpublished) repository [here](https://github.com/amoerie/generic-datatables/tree/v2.0) 

Maybe checkout the solution and start at the partial view _GymMemberList.cshtml under Home.
It supports the notion of creating a powerful datatable against either a IEnumerable of T or even against a REST endpoint. It should work with Datatables 9, it's not been tested with Datatables 10 yet though.

But it's pretty much undocumented, so only do this if you have a lot of time and maybe need some inspiration. 

The link I gave you links to branch v2.0, which I ambitiously started one time but never got the time to finish. There's a full blog post on the main version though, which has a bit more restrictions but is more battle tested. You can read up on that [here](http://amoerie.com/2013/03/08/a-generic-approach-to-data-tables-with-server-side-processing/).

Good luck!
