### ISSUE TITLE
Cannot Render htmltag.Tohtml() nested with Child Elements

### ISSUE THREAD

**Issue by aboah** [amoerie/HtmlBuilders#61]
HtmlTag div = HtmlTags.Div.Id("errorDiv").Class("container");
                HtmlTag h2 = HtmlTags.H2.Style("color", "forestgreen !important").Class("display-3 font-weight-bold").Append(ModelState.ToModelErrorString());
                div.Append(h2);
                return Content(div.ToHtmlString(), "text/html");

My problem is div.ToHtmlString() does not render h2 embedded in div

**Comment by amoerie** [comment]
HtmlTags are immutable!

Try div = div.Append(h2);


Op do 17 jun. 2021 18:09 schreef aboah ***@***.***>:

**Comment by aboah** [comment]
Ok thanks
