### ISSUE TITLE
non breaking spaces

### ISSUE THREAD

**Issue by ortrails** [amoerie/HtmlBuilders#66]
How do you insert a non breaking space as inner html without it being html encoded?

**Comment by amoerie** [comment]
Please see this issue for an answer: https://github.com/amoerie/HtmlBuilders/issues/58

**Comment by ortrails** [comment]
Hey Alexander. When I do that for &nbsp; I get unicode U+00A0 no-break space character. That seems incorrect when i want the &nbsp;

**Comment by amoerie** [comment]
Are you sure they're not equivalent? According to https://en.wikipedia.org/wiki/Non-breaking_space those are the same.
I agree that there is a parsing step that happens and that the nbsp is transformed into `&#xA0;` but is this not, for all intents and purposes, the same?

**Comment by ortrails** [comment]
All I can tell you is since 1999 I've always used the string &nbsp; to
prevent breaking and/or force display of whitespace in the rendered
document. Not sure if the unicode char does the same thing.
