### ISSUE TITLE
No trailing semicolon on style attributes

### ISSUE THREAD

**Issue by ortrails** [amoerie/HtmlBuilders#67]
When I do something like this:
`td = td.Style("vertical-align", "top").Style("width", "25%");`
The resulting style attribute on the cell looks like this:
`<td style="vertical-align:top;width:25%">`
I believe valid HTML requires a trailing semicolon:
`<td style="vertical-align:top;width:25%;">`

Reference https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/style

**Comment by amoerie** [comment]
You're right! I'll see when I can find some time to fix this. I also accept pull requests if you're in a hurry. 😉
