### ISSUE TITLE
HtmlBuilder + MVC "container helper"?

### ISSUE THREAD

**Issue by alexdresko** [amoerie/HtmlBuilders#7]
Is it possible to combine HtmlBuilders with the Q & A here? http://stackoverflow.com/questions/8292497/how-can-i-create-a-html-helper-like-html-beginform

I understand how that SO post works, but not sure how to integrate HtmlBuilder into it.

**Comment by amoerie** [comment]
Sorry to leave you hanging this long, I sort of lost all attention for this library. I ported it to .NET Core now though! If this is still relevant to you, open a new issue. Sorry again!

**Comment by alexdresko** [comment]
No problem. I ended up working with someone to create this: https://github.com/kodefuguru/gutentag

It's similar to this project, but allows creating HTML using c# that looks like this: 

```
var tag = new Div
            {
                {"id", "foo"},
                {"class", "bar"},
                new P
                {
                    "Hello World"
                }
            };
```

Kinda bonkers, really.
