### ISSUE TITLE
TagRenderMode is not possible to set for HtmlTag

### ISSUE THREAD

**Issue by m1dst** [amoerie/HtmlBuilders#8]
I am creating HTML using the HtmlTag class using the Fluent syntax and wanted to write the HTML to a writer using a TagRenderMode of StartTag.  This is possible with the TagBuilder but is not exposed for HtmlTag.  Any chance this could be a supported use case in the future?

The kind of code I'm trying to write is...

```
var portlet = new HtmlTag("div").Class("portlet");
_writer.Write(portlet.ToHtml(TagRenderMode.StartTag));
```

**Comment by amoerie** [comment]
Hello James

HtmlTag contains a method WithTagRenderMode you should be able to use here,
see the latest release notes 😉

**Comment by m1dst** [comment]
Maybe I'm being a dummy....  Aren't these methods private though?

**Comment by m1dst** [comment]
Looks like the following might be a workaround...

`_writer.Write(portlet.Render(Microsoft.AspNetCore.Mvc.Rendering.TagRenderMode.StartTag).ToHtml().ToHtmlString());`

**Comment by amoerie** [comment]
Ah yes, you needed the Render method, my apologies! I wouldn't consider
that a workaround though 🙂
